### ISSUE TITLE
combine every think

### ISSUE THREAD

**Issue by LuckyTurtleDev** [LuckyTurtleDev/m3#48]
We need to glue everything together.
This includes:
* sending level to players, if they join
* timeout for creating solution
* timeout for driving
* retry if player has failed

**Comment by Ipagaxi** [comment]
Line 138 in pc/src/usb.rs needs to be implementet (handling getting protocol event)

**Comment by LuckyTurtleDev** [comment]
>Line 138 in pc/src/usb.rs needs to be implementet (handling getting protocol event)

@Ipagaxi i Did we really need this? After connection establishment the pybade does currently not send any protocol events anymore. So this arm should be never match.
